sudo: required

language: php
php:
  - '7.1'

env:
  global:
    - URI="https://travis-ci.org/BorderCloud/tft-jena-fuseki/builds/$((TRAVIS_JOB_ID - 1))"
    - NAME="Jena Fuseki"
    - SOFTWARE_DESCRIBE="Jena Fuseki"
    - VERSION="3.4.0"
    - SPARQLSCORE_DATABASE="localhost:8080/rdf4j-server/repositories"
#    - SPARQLSCORE_DATABASE="172.17.0.6" #local

services:
  - docker

before_install:
  - docker pull bordercloud/tft-virtuoso7-stable
  - docker pull bordercloud/tft-jena-fuseki
  - docker build -t genji/tomcat -f Dockerfile.tomcat .
  - docker build -t rdf4j -f Dockerfile.rdf4j .

#  - docker pull bordercloud/tft-jena-fuseki

script:
# Deploy TFT
# Run RDF database in order to save tests and results
  -   docker run --privileged --name instance.jena-fuseki -h tft-jena-fuseki -d tft-jena-fuseki

  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable

  -   docker run --privileged --name rdf4j-travis -p 8080:8080 --rm -d rdf4j

##  -   docker run --privileged --name instance.tft_database -d tft-jena-fuseki

## Run quick test
#  -   docker run --privileged --name instance.jena-fuseki -h tft-jena-fuseki -d bordercloud/tft-jena-fuseki
#  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable
#  -   docker run --privileged --name instance.tft_database -d bordercloud/tft-jena-fuseki

  -   git clone --recursive https://github.com/GenjitsuGame/TFT.git
  -   cd TFT
  -   composer install --dev
  -   php ./tft-testsuite -a -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update
  -   php ./tft -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -tt fuseki -tq http://172.17.0.2/test/query -tu http://172.17.0.2/test/update -r ${URI} -o ./junit --softwareName="${NAME}"  --softwareDescribeTag=${VERSION}  --softwareDescribe="${TRAVIS_COMMIT}"
  -   php ./tft-score -t fuseki -q http://${SPARQLSCORE_DATABASE}/test/query -u http://${SPARQLSCORE_DATABASE}/test/update -r  ${URI}
